apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: github-desktop
  namespace: workspaces
spec:
  displayName: Github-Desktop
  description: '[Github Desktop] is an open source Electron-based GitHub app. It is
    written in TypeScript and uses React.'
  category: Development
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/github-desktop-logo.png
  baseImage: lscr.io/linuxserver/github-desktop:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - github-desktop
  - development
