apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: gitqlient
  namespace: workspaces
spec:
  displayName: Gitqlient
  description: '[GitQlient] is a multi-platform Git client originally forked from
    QGit. Nowadays it goes beyond of just a fork and adds a lot of new functionality.'
  category: Development
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/gitqlient-logo.png
  baseImage: lscr.io/linuxserver/gitqlient:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - gitqlient
  - development
