apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: sqlitebrowser
  namespace: workspaces
spec:
  displayName: Sqlitebrowser
  description: '[DB Browser for SQLite] is a high quality, visual, open source tool
    to create, design, and edit database files compatible with SQLite.'
  category: Development
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sqlitebrowser-logo.png
  baseImage: lscr.io/linuxserver/sqlitebrowser:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - sqlitebrowser
  - development
