apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: yaak
  namespace: workspaces
spec:
  displayName: Yaak
  description: yaak is a desktop API client for organizing and executing REST, GraphQL,
    and gRPC requests. It's built using [Tauri](https://tauri.app/), [Rust](https://www.rust-lang.org/),
    and [ReactJS](https://react.dev/).
  category: Development
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/yaak-logo.png
  baseImage: lscr.io/linuxserver/yaak:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - yaak
  - development
