apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: nextcloud
  namespace: workspaces
spec:
  displayName: Nextcloud
  description: nextcloud gives you access to all your files wherever you are.  Where
    are your photos and documents? With Nextcloud you pick a server of your choice,
    at home, in a data center or at a provider. And that is where your files will
    be. Nextcloud runs on that server, protecting your data and giving you access
    from your desktop or mobile devices. Through Nextcloud you also access, sync and
    share your existing data on that FTP drive at the office, a Dropbox or a NAS you
    have at home.
  category: Cloud,Documents
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nextcloud-logo.png
  baseImage: lscr.io/linuxserver/nextcloud:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - nextcloud
  - cloud,documents
