apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: duckstation
  namespace: workspaces
spec:
  displayName: Duckstation
  description: '[DuckStation] is a PS1 Emulator aiming for the best accuracy and game
    support.'
  category: Gaming
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/duckstation-logo.png
  baseImage: lscr.io/linuxserver/duckstation:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - duckstation
  - gaming
