apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: flycast
  namespace: workspaces
spec:
  displayName: Flycast
  description: '[Flycast] is a multi-platform Sega Dreamcast, Naomi, Naomi 2, and
    Atomiswave emulator derived from reicast.'
  category: Gaming
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/flycast-logo.png
  baseImage: lscr.io/linuxserver/flycast:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - flycast
  - gaming
