apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: luanti
  namespace: workspaces
spec:
  displayName: Luanti
  description: luanti (formerly Minetest) is an open source voxel game-creation platform
    with easy modding and game creation
  category: Gaming
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/luanti-logo.png
  baseImage: lscr.io/linuxserver/luanti:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - luanti
  - gaming
