apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: pcsx2
  namespace: workspaces
  annotations:
    streamspace.dev/image-status: pending-migration
spec:
  displayName: Pcsx2
  description: PCSX2 is an open source PS2 Emulator.
  category: Gaming
  baseImage: lscr.io/linuxserver/pcsx2:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  capabilities:
  - Network
  - Clipboard
  tags:
  - pcsx2
  - gaming
