apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: rpcs3
  namespace: workspaces
spec:
  displayName: Rpcs3
  description: '[RPCS3] is a multi-platform open-source Sony PlayStation 3 emulator
    and debugger written in C++ for Windows, Linux, macOS and FreeBSD.'
  category: Gaming
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/rpcs3-logo.png
  baseImage: lscr.io/linuxserver/rpcs3:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - rpcs3
  - gaming
