apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: xemu
  namespace: workspaces
spec:
  displayName: Xemu
  description: '[xemu] is a free and open-source application that emulates the original
    Microsoft Xbox game console, enabling people to play their original Xbox games
    on Windows, macOS, and Linux systems.'
  category: Gaming
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/xemu-logo.png
  baseImage: lscr.io/linuxserver/xemu:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - xemu
  - gaming
