apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: pwndrop
  namespace: workspaces
spec:
  displayName: Pwndrop
  description: pwndrop is a self-deployable file hosting service for sending out red
    teaming payloads or securely sharing your private files over HTTP and WebDAV.
  category: File Sharing,Security
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/pwndrop-logo.png
  baseImage: lscr.io/linuxserver/pwndrop:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - pwndrop
  - file sharing,security
