apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: rustdesk
  namespace: workspaces
spec:
  displayName: Rustdesk
  description: '[RustDesk] is a full-featured open source remote control alternative
    for self-hosting and security with minimal configuration.'
  category: Remote Desktop
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/rustdesk-logo.png
  baseImage: lscr.io/linuxserver/rustdesk:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - rustdesk
  - remote desktop
