apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: webtop
  namespace: workspaces
spec:
  displayName: Webtop
  description: Full Linux desktop environment accessible via web browser. Available
    in multiple distributions and desktop environments.
  category: Remote Desktop
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webtop-logo.png
  baseImage: lscr.io/linuxserver/webtop:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - webtop
  - remote desktop
