apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: openssh-server
  namespace: workspaces
spec:
  displayName: Openssh-Server
  description: openssh-server is a sandboxed environment that allows ssh access without
    giving keys to the entire server. Giving ssh access via private key often means
    giving full access to the server. This container creates a limited and sandboxed
    environment that others can ssh into. The users only have access to the folders
    mapped and the processes running inside this container.
  category: Administration
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/openssh-server-logo.png
  baseImage: lscr.io/linuxserver/openssh-server:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - openssh-server
  - administration
