apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: cura
  namespace: workspaces
spec:
  displayName: Cura
  description: '[UltiMaker Cura] is free, easy-to-use 3D printing software trusted
    by millions of users. Fine-tune your 3D model with 400+ settings for the best
    slicing and printing results.'
  category: Design & Graphics
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/cura-logo.png
  baseImage: lscr.io/linuxserver/cura:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - cura
  - design & graphics
