apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: freecad
  namespace: workspaces
spec:
  displayName: Freecad
  description: '[FreeCAD] is a general-purpose parametric 3D computer-aided design
    (CAD) modeler and a building information modeling (BIM) software application with
    finite element method (FEM) support.'
  category: Design & Graphics
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/freecad-logo.png
  baseImage: lscr.io/linuxserver/freecad:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - freecad
  - design & graphics
