apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: gimp
  namespace: workspaces
spec:
  displayName: Gimp
  description: '[GIMP] is a free and open-source raster graphics editor used for image
    manipulation (retouching) and image editing, free-form drawing, transcoding between
    different image file formats, and more specialized tasks. It is extensible by
    means of plugins, and scriptable.'
  category: Design & Graphics
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/gimp-logo.png
  baseImage: lscr.io/linuxserver/gimp:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - gimp
  - design & graphics
