apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: kicad
  namespace: workspaces
spec:
  displayName: Kicad
  description: '[KiCad] - A Cross Platform and Open Source Electronics Design Automation
    Suite.'
  category: Design & Graphics
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/kicad-logo.png
  baseImage: lscr.io/linuxserver/kicad:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - kicad
  - design & graphics
