apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: krita
  namespace: workspaces
spec:
  displayName: Krita
  description: '[Krita] is a professional FREE and open source painting program. It
    is made by artists that want to see affordable art tools for everyone.'
  category: Design & Graphics
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/krita-logo.png
  baseImage: lscr.io/linuxserver/krita:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - krita
  - design & graphics
