apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: manyfold
  namespace: workspaces
spec:
  displayName: Manyfold
  description: manyfold  is an open source, self-hosted web application for managing
    a collection of 3D models, particularly focused on 3D printing.
  category: Design & Graphics
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/manyfold-logo.png
  baseImage: lscr.io/linuxserver/manyfold:latest
  defaultResources:
    memory: 4Gi
    cpu: 2000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - manyfold
  - design & graphics
