apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: grocy
  namespace: workspaces
spec:
  displayName: Grocy
  description: 'grocy is an ERP system for your kitchen! Cut down on food waste, and
    manage your chores with this brilliant utility.  Keep track of your purchases,
    how much food you are wasting, what chores need doing and what batteries need
    charging with this proudly Open Source tool  For more information on grocy visit
    their website and check it out: https://grocy.info'
  category: Lifestyle
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/grocy-logo.png
  baseImage: lscr.io/linuxserver/grocy:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - grocy
  - lifestyle
