apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: webcord
  namespace: workspaces
spec:
  displayName: Webcord
  description: '[WebCord] can be summarized as a pack of security and privacy hardenings,
    Discord features reimplementations, Electron / Chromium / Discord bugs workarounds,
    stylesheets, internal pages and wrapped https://discord.com page, designed to
    conform with ToS as much as it is possible (or hide the changes that might violate
    it from Discord''s eyes).'
  category: Chat
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webcord-logo.png
  baseImage: lscr.io/linuxserver/webcord:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - webcord
  - chat
