apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: doublecommander
  namespace: workspaces
spec:
  displayName: Doublecommander
  description: '[Double Commander] is a free cross platform open source file manager
    with two panels side by side. It is inspired by Total Commander and features some
    new ideas.'
  category: Administration,Storage
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/doublecommander-logo.png
  baseImage: lscr.io/linuxserver/doublecommander:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - doublecommander
  - administration,storage
