apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: syncthing
  namespace: workspaces
spec:
  displayName: Syncthing
  description: syncthing replaces proprietary sync and cloud services with something
    open, trustworthy and decentralized. Your data is your data alone and you deserve
    to choose where it is stored, if it is shared with some third party and how it's
    transmitted over the Internet.
  category: Backup
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/syncthing-logo.png
  baseImage: lscr.io/linuxserver/syncthing:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - syncthing
  - backup
