apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: ldap-auth
  namespace: workspaces
spec:
  displayName: Ldap-Auth
  description: "ldap-auth software is for authenticating users who request protected\
    \ resources from servers proxied by nginx. It includes a daemon (ldap-auth) that\
    \ communicates with an authentication server, and a webserver daemon that generates\
    \ an authentication cookie based on the user\u2019s credentials. The daemons are\
    \ written in Python for use with a Lightweight Directory Access Protocol (LDAP)\
    \ authentication server (OpenLDAP or Microsoft Windows Active Directory 2003 and\
    \ 2012)."
  category: Administration,Security
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ldap-auth-logo.png
  baseImage: lscr.io/linuxserver/ldap-auth:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - ldap-auth
  - administration,security
