apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: healthchecks
  namespace: workspaces
spec:
  displayName: Healthchecks
  description: healthchecks is a watchdog for your cron jobs. It's a web server that
    listens for pings from your cron jobs, plus a web interface.
  category: Monitoring
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/healthchecks-logo.png
  baseImage: lscr.io/linuxserver/healthchecks:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - healthchecks
  - monitoring
