apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: speedtest-tracker
  namespace: workspaces
spec:
  displayName: Speedtest-Tracker
  description: speedtest-tracker is a self-hosted internet performance tracking application
    that runs speedtest checks against Ookla's Speedtest service.
  category: Monitoring
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/speedtest-tracker-logo.png
  baseImage: lscr.io/linuxserver/speedtest-tracker:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - speedtest-tracker
  - monitoring
