apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: bazarr
  namespace: workspaces
spec:
  displayName: Bazarr
  description: bazarr is a companion application to Sonarr and Radarr. It can manage
    and download subtitles based on your requirements. You define your preferences
    by TV show or movie and Bazarr takes care of everything for you.
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/bazarr-logo.png
  baseImage: lscr.io/linuxserver/bazarr:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - bazarr
  - media
