apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: beets
  namespace: workspaces
spec:
  displayName: Beets
  description: beets is a music library manager and not, for the most part, a music
    player. It does include a simple player plugin and an experimental Web-based player,
    but it generally leaves actual sound-reproduction to specialized tools.
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/beets-logo.png
  baseImage: lscr.io/linuxserver/beets:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - beets
  - media
