apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: doplarr
  namespace: workspaces
spec:
  displayName: Doplarr
  description: doplarr is an *arr request bot for Discord."
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/doplarr-logo.png
  baseImage: lscr.io/linuxserver/doplarr:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - doplarr
  - media
