apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: lollypop
  namespace: workspaces
spec:
  displayName: Lollypop
  description: '[Lollypop] is a lightweight modern music player designed to work excellently
    on the GNOME desktop environment.'
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/lollypop-logo.png
  baseImage: lscr.io/linuxserver/lollypop:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - lollypop
  - media
