apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: medusa
  namespace: workspaces
spec:
  displayName: Medusa
  description: medusa is an automatic Video Library Manager for TV Shows. It watches
    for new episodes of your favorite shows, and when they are posted it does its
    magic.
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/medusa-logo.png
  baseImage: lscr.io/linuxserver/medusa:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - medusa
  - media
