apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: sickgear
  namespace: workspaces
spec:
  displayName: Sickgear
  description: '[SickGear] provides management of TV shows and/or Anime, it detects
    new episodes, links downloader apps, and more..  For more information on SickGear
    visit their website and check it out: https://github.com/SickGear/SickGear'
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sickgear-logo.png
  baseImage: lscr.io/linuxserver/sickgear:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - sickgear
  - media
