apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: sonarr
  namespace: workspaces
spec:
  displayName: Sonarr
  description: sonarr (formerly NZBdrone) is a PVR for usenet and bittorrent users.
    It can monitor multiple RSS feeds for new episodes of your favorite shows and
    will grab, sort and rename them. It can also be configured to automatically upgrade
    the quality of files already downloaded when a better quality format becomes available.
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sonarr-logo.png
  baseImage: lscr.io/linuxserver/sonarr:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - sonarr
  - media
