apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: spotube
  namespace: workspaces
spec:
  displayName: Spotube
  description: '[Spotube] is an open source, cross-platform Spotify client compatible
    across multiple platforms utilizing Spotify''s data API and YouTube, Piped.video
    or JioSaavn as an audio source, eliminating the need for Spotify Premium'
  category: Media
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/spotube-logo.png
  baseImage: lscr.io/linuxserver/spotube:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - spotube
  - media
