apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: sealskin
  namespace: workspaces
spec:
  displayName: Sealskin
  description: "[Sealskin] is a self-hosted, client-server platform that enables users\
    \ to run powerful, containerized desktop applications streamed directly to a web\
    \ browser. It uses a browser extension to intercept user actions\u2014such as\
    \ clicking a link or downloading a file and redirects them to a secure, isolated\
    \ application environment running on a remote server."
  category: Remote Desktop, Business
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/sealskin-logo.png
  baseImage: lscr.io/linuxserver/sealskin:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - sealskin
  - remote desktop, business
