apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: wireshark
  namespace: workspaces
spec:
  displayName: Wireshark
  description: "[Wireshark] is the world\u2019s foremost and widely-used network protocol\
    \ analyzer. It lets you see what\u2019s happening on your network at a microscopic\
    \ level and is the de facto (and often de jure) standard across many commercial\
    \ and non-profit enterprises, government agencies, and educational institutions.\
    \ Wireshark development thrives thanks to the volunteer contributions of networking\
    \ experts around the globe and is the continuation of a project started by Gerald\
    \ Combs in 1998."
  category: Network
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/wireshark-logo.png
  baseImage: lscr.io/linuxserver/wireshark:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - wireshark
  - network
