apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: airsonic-advanced
  namespace: workspaces
spec:
  displayName: Airsonic-Advanced
  description: airsonic-advanced is a free, web-based media streamer, providing ubiquitious
    access to your music. Use it to share your music with friends, or to listen to
    your own music while at work. You can stream to multiple players simultaneously,
    for instance to one player in your kitchen and another in your living room.
  category: Media Servers,Music
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/airsonic-advanced-logo.png
  baseImage: lscr.io/linuxserver/airsonic-advanced:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - airsonic-advanced
  - media servers,music
