apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: changedetection.io
  namespace: workspaces
spec:
  displayName: Changedetection.Io
  description: changedetection.io provides free, open-source web page monitoring,
    notification and change detection.
  category: Web Tools,Automation
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/changedetection.io-logo.png
  baseImage: lscr.io/linuxserver/changedetection.io:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - changedetection.io
  - web tools,automation
