apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: diskover
  namespace: workspaces
spec:
  displayName: Diskover
  description: diskover is an open source file system indexer that uses Elasticsearch
    to index and manage data across heterogeneous storage systems.
  category: Storage,Monitoring
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/diskover-logo.png
  baseImage: lscr.io/linuxserver/diskover:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - diskover
  - storage,monitoring
