apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: mylar3
  namespace: workspaces
spec:
  displayName: Mylar3
  description: mylar3 is an automated Comic Book downloader (cbr/cbz) for use with
    NZB and torrents written in python. It supports SABnzbd, NZBGET, and many torrent
    clients in addition to DDL.
  category: Books,Media Management
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/mylar3-logo.png
  baseImage: lscr.io/linuxserver/mylar3:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - mylar3
  - books,media management
