apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: chrome
  namespace: workspaces
spec:
  displayName: Chrome
  description: '[Chrome] is the official web browser from Google, built to be fast,
    secure, and customizable.'
  category: Web Browsers
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/chrome-logo.png
  baseImage: lscr.io/linuxserver/chrome:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - chrome
  - web browsers
