apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: chromium
  namespace: workspaces
spec:
  displayName: Chromium
  description: '[Chromium] is an open-source browser project that aims to build a
    safer, faster, and more stable way for all users to experience the web.'
  category: Web Browsers
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/chromium-logo.png
  baseImage: lscr.io/linuxserver/chromium:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - chromium
  - web browsers
