apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: firefox
  namespace: workspaces
spec:
  displayName: Firefox
  description: '[Firefox] Browser, also known as Mozilla Firefox or simply Firefox,
    is a free and open-source web browser developed by the Mozilla Foundation and
    its subsidiary, the Mozilla Corporation. Firefox uses the Gecko layout engine
    to render web pages, which implements current and anticipated web standards.'
  category: Web Browsers
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/firefox-logo.png
  baseImage: lscr.io/linuxserver/firefox:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - firefox
  - web browsers
