apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: librewolf
  namespace: workspaces
spec:
  displayName: Librewolf
  description: '[LibreWolf] is a custom and independent version of Firefox, with the
    primary goals of privacy, security and user freedom. LibreWolf also aims to remove
    all the telemetry, data collection and annoyances, as well as disabling anti-freedom
    features like DRM.'
  category: Web Browsers
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/librewolf-logo.png
  baseImage: lscr.io/linuxserver/librewolf:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - librewolf
  - web browsers
