apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: msedge
  namespace: workspaces
spec:
  displayName: Msedge
  description: '[Microsoft Edge] is a cross-platform web browser developed by Microsoft
    and based on Chromium.'
  category: Web Browsers
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/msedge-logo.png
  baseImage: lscr.io/linuxserver/msedge:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - msedge
  - web browsers
