apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: opera
  namespace: workspaces
spec:
  displayName: Opera
  description: '[Opera] is a multi-platform web browser developed by its namesake
    company Opera. The browser is based on Chromium, but distinguishes itself from
    other Chromium-based browsers (Chrome, Edge, etc.) through its user interface
    and other features.'
  category: Web Browsers
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/opera-logo.png
  baseImage: lscr.io/linuxserver/opera:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - opera
  - web browsers
