apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: vivaldi
  namespace: workspaces
spec:
  displayName: Vivaldi
  description: '[Vivaldi] is a Norwegian freeware, cross-platform web browser with
    a built-in email client developed by Vivaldi Technologies.'
  category: Web Browsers
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/vivaldi-logo.png
  baseImage: lscr.io/linuxserver/vivaldi:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - vivaldi
  - web browsers
