apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: planka
  namespace: workspaces
spec:
  displayName: Planka
  description: planka is an elegant open source project tracking tool.
  category: Content Management,Business
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/planka-logo.png
  baseImage: lscr.io/linuxserver/planka:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - planka
  - content management,business
