apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: prowlarr
  namespace: workspaces
spec:
  displayName: Prowlarr
  description: prowlarr is a indexer manager/proxy built on the popular arr .net/reactjs
    base stack to integrate with your various PVR apps. Prowlarr supports both Torrent
    Trackers and Usenet Indexers. It integrates seamlessly with Sonarr, Radarr, Lidarr,
    and Readarr offering complete management of your indexers with no per app Indexer
    setup required (we do it all).
  category: Indexers
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/prowlarr-logo.png
  baseImage: lscr.io/linuxserver/prowlarr:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - prowlarr
  - indexers
