apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: ardour
  namespace: workspaces
spec:
  displayName: Ardour
  description: '[Ardour] is an open source, collaborative effort of a worldwide team
    including musicians, programmers, and professional recording engineers.'
  category: Audio & Video
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ardour-logo.png
  baseImage: lscr.io/linuxserver/ardour:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - ardour
  - audio & video
