apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: audacity
  namespace: workspaces
spec:
  displayName: Audacity
  description: '[Audacity] is an easy-to-use, multi-track audio editor and recorder.
    Developed by a group of volunteers as open source.'
  category: Audio & Video
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/audacity-logo.png
  baseImage: lscr.io/linuxserver/audacity:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - audacity
  - audio & video
