apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: kdenlive
  namespace: workspaces
spec:
  displayName: Kdenlive
  description: '[Kdenlive] is a powerful free and open source cross-platform video
    editing program made by the KDE community. Feature rich and production ready.'
  category: Audio & Video
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/kdenlive-logo.png
  baseImage: lscr.io/linuxserver/kdenlive:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - kdenlive
  - audio & video
