apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: minisatip
  namespace: workspaces
spec:
  displayName: Minisatip
  description: minisatip is a multi-threaded satip server version 1.2 that runs under
    Linux and it was tested with DVB-S, DVB-S2, DVB-T, DVB-T2, DVB-C, DVB-C2, ATSC
    and ISDB-T cards.
  category: Audio & Video
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/minisatip-logo.png
  baseImage: lscr.io/linuxserver/minisatip:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - minisatip
  - audio & video
