apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: openshot
  namespace: workspaces
  annotations:
    streamspace.dev/image-status: pending-migration
spec:
  displayName: Openshot
  description: OpenShot Video Editor is an award-winning free and open-source video
    editor for Linux, Mac, and Windows, and is dedicated to delivering high quality
    video editing and animation solutions to the world.
  category: Audio & Video
  baseImage: lscr.io/linuxserver/openshot:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  capabilities:
  - Network
  - Clipboard
  tags:
  - openshot
  - audio--video
