apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: shotcut
  namespace: workspaces
spec:
  displayName: Shotcut
  description: shotcut is a free, open source, cross-platform video editor.
  category: Audio & Video
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/shotcut-logo.png
  baseImage: lscr.io/linuxserver/shotcut:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - shotcut
  - audio & video
