apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: synclounge
  namespace: workspaces
spec:
  displayName: Synclounge
  description: synclounge is a third party tool that allows you to watch Plex in sync
    with your friends/family, wherever you are.
  category: Audio & Video
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/synclounge-logo.png
  baseImage: lscr.io/linuxserver/synclounge:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - synclounge
  - audio & video
