apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: webgrabplus
  namespace: workspaces
spec:
  displayName: Webgrabplus
  description: webgrabplus is a multi-site incremental xmltv epg grabber. It collects
    tv-program guide data from selected tvguide sites for your favourite channels.
  category: Audio & Video
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/webgrabplus-logo.png
  baseImage: lscr.io/linuxserver/webgrabplus:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - webgrabplus
  - audio & video
