apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: davos
  namespace: workspaces
spec:
  displayName: Davos
  description: davos is an FTP automation tool that periodically scans given host
    locations for new files. It can be configured for various purposes, including
    listening for specific files to appear in the host location, ready for it to download
    and then move, if required. It also supports completion notifications as well
    as downstream API calls, to further the workflow.
  category: File Management
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/davos-logo.png
  baseImage: lscr.io/linuxserver/davos:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - davos
  - file management
