apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: filezilla
  namespace: workspaces
spec:
  displayName: Filezilla
  description: '[FIleZilla] Client is a fast and reliable cross-platform FTP, FTPS
    and SFTP client with lots of useful features and an intuitive graphical user interface.'
  category: File Management
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/filezilla-logo.png
  baseImage: lscr.io/linuxserver/filezilla:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - filezilla
  - file management
