apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: nzbget
  namespace: workspaces
spec:
  displayName: Nzbget
  description: nzbget is a usenet downloader, written in C++ and designed with performance
    in mind to achieve maximum download speed by using very little system resources.
  category: File Management
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/nzbget-logo.png
  baseImage: lscr.io/linuxserver/nzbget:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - nzbget
  - file management
