apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: qbittorrent
  namespace: workspaces
spec:
  displayName: Qbittorrent
  description: "The qbittorrent project aims to provide an open-source software alternative\
    \ to \xB5Torrent. qBittorrent is based on the Qt toolkit and libtorrent-rasterbar\
    \ library."
  category: File Management
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/qbittorrent-logo.png
  baseImage: lscr.io/linuxserver/qbittorrent:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - qbittorrent
  - file management
