apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: transmission
  namespace: workspaces
spec:
  displayName: Transmission
  description: "transmission is designed for easy, powerful use. Transmission has\
    \ the features you want from a BitTorrent client: encryption, a web interface,\
    \ peer exchange, magnet links, DHT, \xB5TP, UPnP and NAT-PMP port forwarding,\
    \ webseed support, watch directories, tracker editing, global and per-torrent\
    \ speed limits, and more."
  category: File Management
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/transmission-logo.png
  baseImage: lscr.io/linuxserver/transmission:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - transmission
  - file management
