apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: faster-whisper
  namespace: workspaces
spec:
  displayName: Faster-Whisper
  description: faster-whisper is a reimplementation of OpenAI's Whisper model using
    CTranslate2, which is a fast inference engine for Transformer models. This container
    provides a Wyoming protocol server for faster-whisper.
  category: AI & ML
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/faster-whisper-logo.png
  baseImage: lscr.io/linuxserver/faster-whisper:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - faster-whisper
  - ai & ml
