apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: piper
  namespace: workspaces
spec:
  displayName: Piper
  description: piper is a fast, local neural text to speech system that sounds great
    and is optimized for the Raspberry Pi 4. This container provides a Wyoming protocol
    server for Piper.
  category: AI & ML
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/piper-logo.png
  baseImage: lscr.io/linuxserver/piper:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - piper
  - ai & ml
