apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: swag
  namespace: workspaces
spec:
  displayName: Swag
  description: "SWAG - Secure Web Application Gateway (formerly known as letsencrypt,\
    \ no relation to Let's Encrypt\u2122) sets up an Nginx webserver and reverse proxy\
    \ with php support and a built-in certbot client that automates free SSL server\
    \ certificate generation and renewal processes (Let's Encrypt and ZeroSSL). It\
    \ also contains fail2ban for intrusion prevention."
  category: Reverse Proxy
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/swag-logo.png
  baseImage: lscr.io/linuxserver/swag:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - swag
  - reverse proxy
