apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: budge
  namespace: workspaces
spec:
  displayName: Budge
  description: budge is an open source 'budgeting with envelopes' personal finance
    app.
  category: Productivity
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/budge-logo.png
  baseImage: lscr.io/linuxserver/budge:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - budge
  - productivity
