apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: hedgedoc
  namespace: workspaces
spec:
  displayName: Hedgedoc
  description: '[HedgeDoc] gives you access to all your files wherever you are.  HedgeDoc
    is a real-time, multi-platform collaborative markdown note editor.  This means
    that you can write notes with other people on your desktop, tablet or even on
    the phone.  You can sign-in via multiple auth providers like Facebook, Twitter,
    GitHub and many more on the homepage.'
  category: Productivity
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/hedgedoc-logo.png
  baseImage: lscr.io/linuxserver/hedgedoc:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - hedgedoc
  - productivity
