apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: joplin
  namespace: workspaces
spec:
  displayName: Joplin
  description: '[Joplin] is a free, open source note taking and to-do application,
    which can handle a large number of notes organised into notebooks.'
  category: Productivity
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/joplin-logo.png
  baseImage: lscr.io/linuxserver/joplin:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - joplin
  - productivity
