apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: obsidian
  namespace: workspaces
spec:
  displayName: Obsidian
  description: '[Obsidian] is a note-taking app that lets you create, link, and organize
    your notes on your device, with hundreds of plugins and themes to customize your
    workflow. You can also publish your notes online, access them offline, and sync
    them securely with end-to-end encryption.'
  category: Productivity
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/obsidian-logo.png
  baseImage: lscr.io/linuxserver/obsidian:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - obsidian
  - productivity
