apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: zotero
  namespace: workspaces
spec:
  displayName: Zotero
  description: '[Zotero] is a free, easy-to-use tool to help you collect, organize,
    annotate, cite, and share research.'
  category: Productivity
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/zotero-logo.png
  baseImage: lscr.io/linuxserver/zotero:latest
  defaultResources:
    memory: 3Gi
    cpu: 1500m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: true
    port: 3000
  capabilities:
  - Network
  - Clipboard
  tags:
  - zotero
  - productivity
