apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: netbox
  namespace: workspaces
spec:
  displayName: Netbox
  description: netbox is an IP address management (IPAM) and data center infrastructure
    management (DCIM) tool. Initially conceived by the network engineering team at
    DigitalOcean, NetBox was developed specifically to address the needs of network
    and infrastructure engineers. It is intended to function as a domain-specific
    source of truth for network operations.
  category: Administration,Business
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/netbox-logo.png
  baseImage: lscr.io/linuxserver/netbox:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - netbox
  - administration,business
