apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: thelounge
  namespace: workspaces
spec:
  displayName: Thelounge
  description: thelounge (a fork of shoutIRC) is a web IRC client that you host on
    your own server.
  category: IRC,Chat
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/thelounge-logo.png
  baseImage: lscr.io/linuxserver/thelounge:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - thelounge
  - irc,chat
