apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: emby
  namespace: workspaces
spec:
  displayName: Emby
  description: emby organizes video, music, live TV, and photos from personal media
    libraries and streams them to smart TVs, streaming boxes and mobile devices. This
    container is packaged as a standalone emby Media Server.
  category: Media Servers,Music,Audiobooks
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/emby-logo.png
  baseImage: lscr.io/linuxserver/emby:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - emby
  - media servers,music,audiobooks
