apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: jellyfin
  namespace: workspaces
spec:
  displayName: Jellyfin
  description: 'jellyfin is a Free Software Media System that puts you in control
    of managing and streaming your media. It is an alternative to the proprietary
    Emby and Plex, to provide media from a dedicated server to end-user devices via
    multiple apps. Jellyfin is descended from Emby''s 3.5.2 release and ported to
    the .NET Core framework to enable full cross-platform support. There are no strings
    attached, no premium licenses or features, and no hidden agendas: just a team
    who want to build something better an'
  category: Media Servers,Music,Audiobooks
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/jellyfin-logo.png
  baseImage: lscr.io/linuxserver/jellyfin:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - jellyfin
  - media servers,music,audiobooks
