apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: habridge
  namespace: workspaces
spec:
  displayName: Habridge
  description: habridge emulates Philips Hue API to other home automation gateways
    such as an Amazon Echo/Dot Gen 1 (gen 2 has issues discovering ha-bridge) or other
    systems that support Philips Hue. The Bridge handles basic commands such as On,
    Off and brightness commands of the hue protocol. This bridge can control most
    devices that have a distinct API.
  category: Automation
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/habridge-logo.png
  baseImage: lscr.io/linuxserver/habridge:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - habridge
  - automation
