apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: ungoogled-chromium
  namespace: workspaces
  annotations:
    streamspace.dev/image-status: pending-migration
spec:
  displayName: Ungoogled-Chromium
  description: Ungoogled Chromium is Google Chromium, sans dependency on Google web
    services.
  category: Web Browsers
  baseImage: lscr.io/linuxserver/ungoogled-chromium:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  capabilities:
  - Network
  - Clipboard
  tags:
  - ungoogled-chromium
  - web-browsers
