apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: zen
  namespace: workspaces
  annotations:
    streamspace.dev/image-status: pending-migration
spec:
  displayName: Zen
  description: Zen Browser is a free and open-source fork of Mozilla Firefox with
    a focus on privacy, customizability and design.
  category: Web Browsers
  baseImage: lscr.io/linuxserver/zen:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: vnc
    containerPort: 3000
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  capabilities:
  - Network
  - Clipboard
  tags:
  - zen
  - web-browsers
