apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: xbackbone
  namespace: workspaces
spec:
  displayName: Xbackbone
  description: xbackbone is a simple, self-hosted, lightweight PHP file manager that
    support the instant sharing tool ShareX and *NIX systems. It supports uploading
    and displaying images, GIF, video, code, formatted text, and file downloading
    and uploading. Also have a web UI with multi user management, past uploads history
    and search support.
  category: File Sharing
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/xbackbone-logo.png
  baseImage: lscr.io/linuxserver/xbackbone:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - xbackbone
  - file sharing
