apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: limnoria
  namespace: workspaces
spec:
  displayName: Limnoria
  description: limnoria A robust, full-featured, and user/programmer-friendly Python
    IRC bot, with many existing plugins. Successor of the well-known Supybot.
  category: Communication
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/limnoria-logo.png
  baseImage: lscr.io/linuxserver/limnoria:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - limnoria
  - communication
