apiVersion: stream.space/v1alpha1
kind: Template
metadata:
  name: ngircd
  namespace: workspaces
spec:
  displayName: Ngircd
  description: ngircd is a free, portable and lightweight Internet Relay Chat server
    for small or private networks, developed under the GNU General Public License
    (GPL). It is easy to configure, can cope with dynamic IP addresses, and supports
    IPv6, SSL-protected connections as well as PAM for authentication. It is written
    from scratch and not based on the original IRCd.
  category: Communication
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/ngircd-logo.png
  baseImage: lscr.io/linuxserver/ngircd:latest
  defaultResources:
    memory: 2Gi
    cpu: 1000m
  ports:
  - name: http
    containerPort: 8080
    protocol: TCP
  env:
  - name: PUID
    value: '1000'
  - name: PGID
    value: '1000'
  - name: TZ
    value: America/New_York
  volumeMounts:
  - name: user-home
    mountPath: /config
  kasmvnc:
    enabled: false
    port: 8080
  capabilities:
  - Network
  - Clipboard
  tags:
  - ngircd
  - communication
